[build]
  publish = "docs"
  command = "hugo"

[build.environment]
  HUGO_VERSION = "0.55.5"

[context.production.environment]
  HUGO_BASEURL = "https://decentralized-web.info/"

[context.deploy-preview]
  command = "hugo -b"

[context.deploy-preview.environment]
  HUGO_ENABLEGITINFO = "true"

[context.branch-deplpy]
  command = "hugo -b $DEPLOY_PRIME_URL"

[context.branch-deploy.environment]
  HUGO_ENABLEGITINFO = "true"

